# Generated by Django 5.0.1 on 2025-03-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_assessmentsubmission_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='certificate_generated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
